// import { Article, Author, Category, Region } from '@/types'

// export const mockCategories: Partial<Category>[] = [
//   { id: 'cat-1', name: 'Elections', slug: 'elections', color: '#e74c3c', icon: '🗳️', description: 'Election coverage, results, and analysis.' },
//   { id: 'cat-2', name: 'Parliament', slug: 'parliament', color: '#3498db', icon: '🏛️', description: 'Parliamentary sessions, debates, and legislation.' },
//   { id: 'cat-3', name: 'International', slug: 'international', color: '#9b59b6', icon: '🌍', description: 'Global affairs and foreign policy.' },
//   { id: 'cat-4', name: 'Policy & Law', slug: 'policy', color: '#e67e22', icon: '⚖️', description: 'Laws, regulations, and government policy.' },
//   { id: 'cat-5', name: 'Defense', slug: 'defense', color: '#2ecc71', icon: '🪖', description: 'Military affairs and national security.' },
//   { id: 'cat-6', name: 'Opinion', slug: 'opinion', color: '#c9a84c', icon: '💬', description: 'Columns, editorials, and commentary.' },
//   { id: 'cat-7', name: 'Data & Analysis', slug: 'data', color: '#1abc9c', icon: '📊', description: 'Data-driven political reporting.' },
//   { id: 'cat-8', name: 'Interviews', slug: 'interviews', color: '#e91e63', icon: '🎙️', description: 'In-depth interviews with political figures.' },
// ]

// export const mockRegions: Partial<Region>[] = [
//   { id: 'reg-1', name: 'Asia', slug: 'asia', description: 'News and analysis from across the Asian continent.' },
//   { id: 'reg-2', name: 'US & Canada', slug: 'us-canada', description: 'Political developments in North America.' },
//   { id: 'reg-3', name: 'Europe', slug: 'europe', description: 'Reports from the European Union and beyond.' },
//   { id: 'reg-4', name: 'Middle East', slug: 'middle-east', description: 'Geopolitics and conflict reporting from the Middle East.' },
//   { id: 'reg-5', name: 'Africa', slug: 'africa', description: 'Updates on African governance and economics.' },
// ]

// export const mockAuthors: Partial<Author>[] = [
//   {
//     id: 'author-1',
//     name: 'Sophea Chan',
//     slug: 'sophea-chan',
//     role: 'Senior Political Correspondent',
//     bio: 'Sophea Chan has covered Cambodian politics for over 15 years, specializing in electoral systems and parliamentary affairs.',
//     avatar: { id: 'media-a1', filename: 'sophea.jpg', url: 'https://picsum.photos/seed/sophea/200/200', alt: 'Sophea Chan', width: 200, height: 200 },
//     twitter: 'sophea_tribune',
//     email: 'sophea@thetribune.com',
//   },
//   {
//     id: 'author-2',
//     name: 'Dara Pich',
//     slug: 'dara-pich',
//     role: 'International Affairs Editor',
//     bio: 'Dara Pich leads The Tribune\'s international desk, reporting on ASEAN diplomacy and global geopolitics.',
//     avatar: { id: 'media-a2', filename: 'dara.jpg', url: 'https://picsum.photos/seed/dara/200/200', alt: 'Dara Pich', width: 200, height: 200 },
//     twitter: 'dara_tribune',
//     email: 'dara@thetribune.com',
//   },
//   {
//     id: 'author-3',
//     name: 'Maly Ros',
//     slug: 'maly-ros',
//     role: 'Data & Investigations Reporter',
//     bio: 'Maly Ros leads data investigations, turning complex government datasets into compelling public-interest stories.',
//     avatar: { id: 'media-a3', filename: 'maly.jpg', url: 'https://picsum.photos/seed/maly/200/200', alt: 'Maly Ros', width: 200, height: 200 },
//     twitter: 'maly_tribune',
//     email: 'maly@thetribune.com',
//   },
// ]

// const cat = (id: string) => mockCategories.find((c) => c.id === id) as any
// const auth = (id: string) => mockAuthors.find((a) => a.id === id) as any
// const reg = (id: string) => mockRegions.find((r) => r.id === id) as any

// export const mockArticles: Partial<Article>[] = [
//   {
//     id: 'art-1',
//     title: 'Parliament Votes to Extend Emergency Powers for Third Consecutive Year',
//     slug: 'parliament-votes-extend-emergency-powers',
//     excerpt: 'The lower house passed a resolution extending executive emergency powers by a margin of 87 votes, drawing fierce opposition from civil society groups.',
//     coverImage: { url: 'https://images.unsplash.com/photo-1529107386311-07b54f597bb3?q=80&w=2000&auto=format&fit=crop', alt: 'Parliament building at night' },
//     category: cat('cat-2'),
//     author: auth('author-1'),
//     status: 'published',
//     isBreaking: true,
//     isFeatured: true,
//     language: 'all',
//     publishedAt: '2026-04-12T04:00:00Z',
//     readTime: 6,
//     tags: [{ tag: 'parliament' }, { tag: 'emergency powers' }, { tag: 'legislation' }],
//     createdAt: '2026-04-12T04:00:00Z',
//     updatedAt: '2026-04-12T04:00:00Z',
//   },
//   {
//     id: 'art-2',
//     title: 'Opposition Leader Calls for Snap Election Amid Economic Crisis',
//     slug: 'opposition-leader-calls-snap-election-economic-crisis',
//     excerpt: 'In a strongly worded statement, the opposition leader demanded the government dissolve parliament and call for fresh elections within 90 days.',
//     coverImage: { url: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?q=80&w=2000&auto=format&fit=crop', alt: 'Opposition rally with banners' },
//     category: cat('cat-1'),
//     author: auth('author-1'),
//     status: 'published',
//     isBreaking: true,
//     isFeatured: true,
//     publishedAt: '2026-04-11T10:00:00Z',
//     readTime: 5,
//     tags: [{ tag: 'elections' }, { tag: 'opposition' }, { tag: 'economy' }],
//     createdAt: '2026-04-11T10:00:00Z',
//     updatedAt: '2026-04-11T10:00:00Z',
//   },
//   {
//     id: 'art-3',
//     title: 'Foreign Minister Signs Historic Trade Deal with Regional Bloc',
//     slug: 'foreign-minister-signs-historic-trade-deal-regional-bloc',
//     excerpt: 'After 18 months of negotiations, the landmark agreement will eliminate tariffs on over 4,000 goods and open new corridors for regional investment.',
//     coverImage: { url: 'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?q=80&w=2000&auto=format&fit=crop', alt: 'ministers signing agreement' },
//     category: cat('cat-3'),
//     author: auth('author-2'),
//     status: 'published',
//     isBreaking: false,
//     isFeatured: true,
//     publishedAt: '2026-04-10T08:30:00Z',
//     readTime: 7,
//     tags: [{ tag: 'trade' }, { tag: 'ASEAN' }, { tag: 'international' }],
//     createdAt: '2026-04-10T08:30:00Z',
//     updatedAt: '2026-04-10T08:30:00Z',
//   },
//   {
//     id: 'art-4',
//     title: 'Supreme Court Rules Against Government in Landmark Privacy Case',
//     slug: 'supreme-court-rules-against-government-landmark-privacy-case',
//     excerpt: 'The court\'s 6-3 ruling found that mass surveillance programs violated constitutional privacy rights, ordering an immediate suspension of data collection.',
//     coverImage: { url: 'https://images.unsplash.com/photo-1589216532372-1c2a11f90e6a?q=80&w=2000&auto=format&fit=crop', alt: 'Supreme court exterior' },
//     category: cat('cat-4'),
//     author: auth('author-1'),
//     status: 'published',
//     isBreaking: false,
//     isFeatured: false,
//     publishedAt: '2026-04-09T14:00:00Z',
//     readTime: 8,
//     tags: [{ tag: 'supreme court' }, { tag: 'privacy' }, { tag: 'ruling' }],
//     createdAt: '2026-04-09T14:00:00Z',
//     updatedAt: '2026-04-09T14:00:00Z',
//   },
//   {
//     id: 'art-5',
//     title: 'Defense Budget Increases 12% as Regional Tensions Escalate',
//     slug: 'defense-budget-increases-12-percent-regional-tensions',
//     excerpt: 'The Ministry of National Defense released its annual budget request citing heightened maritime disputes and cross-border incidents as primary drivers.',
//     coverImage: { url: 'https://images.unsplash.com/photo-1575318634028-6a0cfcb60c59?q=80&w=2000&auto=format&fit=crop', alt: 'military personnel at ceremony' },
//     category: cat('cat-5'),
//     author: auth('author-2'),
//     status: 'published',
//     isBreaking: false,
//     isFeatured: false,
//     publishedAt: '2026-04-08T09:00:00Z',
//     readTime: 5,
//     tags: [{ tag: 'defense' }, { tag: 'budget' }, { tag: 'security' }],
//     createdAt: '2026-04-08T09:00:00Z',
//     updatedAt: '2026-04-08T09:00:00Z',
//   },
//   {
//     id: 'art-6',
//     title: 'Exclusive: Inside the Coalition Negotiations That Lasted 72 Hours',
//     slug: 'exclusive-inside-coalition-negotiations-72-hours',
//     excerpt: 'Our reporters gained rare access to the closed-door sessions that produced the most fragile governing coalition in the nation\'s modern history.',
//     coverImage: { url: 'https://images.unsplash.com/photo-1560174038-da43ac74f01b?q=80&w=2000&auto=format&fit=crop', alt: 'politicians in conference room' },
//     category: cat('cat-8'),
//     author: auth('author-1'),
//     status: 'published',
//     isBreaking: false,
//     isFeatured: false,
//     publishedAt: '2026-04-07T11:00:00Z',
//     readTime: 12,
//     tags: [{ tag: 'coalition' }, { tag: 'exclusive' }, { tag: 'interviews' }],
//     createdAt: '2026-04-07T11:00:00Z',
//     updatedAt: '2026-04-07T11:00:00Z',
//   },
//   {
//     id: 'art-7',
//     title: 'Data Analysis: How Voter Turnout Has Shifted in the Last Decade',
//     slug: 'data-analysis-voter-turnout-shifted-last-decade',
//     excerpt: 'A deep-dive into official election commission data reveals a 22% decline in youth voter participation since 2016, with stark urban-rural disparities.',
//     coverImage: { url: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?q=80&w=2000&auto=format&fit=crop', alt: 'data visualization on screen' },
//     category: cat('cat-7'),
//     author: auth('author-3'),
//     status: 'published',
//     isBreaking: false,
//     isFeatured: false,
//     publishedAt: '2026-04-06T13:00:00Z',
//     readTime: 10,
//     tags: [{ tag: 'data' }, { tag: 'elections' }, { tag: 'analysis' }],
//     createdAt: '2026-04-06T13:00:00Z',
//     updatedAt: '2026-04-06T13:00:00Z',
//   },
//   {
//     id: 'art-8',
//     title: 'Prime Minister Reshuffles Cabinet in Surprise Midnight Announcement',
//     slug: 'prime-minister-reshuffles-cabinet-surprise-midnight-announcement',
//     excerpt: 'Seven ministries changed hands in the unexpected reshuffle, with three senior ministers removed and two new faces from the private sector appointed.',
//     coverImage: { url: 'https://images.unsplash.com/photo-1541873676-a181ecdc5a39?q=80&w=2000&auto=format&fit=crop', alt: 'prime minister at podium' },
//     category: cat('cat-2'),
//     author: auth('author-1'),
//     status: 'published',
//     isBreaking: true,
//     isFeatured: false,
//     publishedAt: '2026-04-05T00:30:00Z',
//     readTime: 6,
//     tags: [{ tag: 'cabinet' }, { tag: 'prime minister' }, { tag: 'reshuffle' }],
//     createdAt: '2026-04-05T00:30:00Z',
//     updatedAt: '2026-04-05T00:30:00Z',
//   },
//   {
//     id: 'art-9',
//     title: 'Opposition Party Splits Over Constitutional Reform Proposal',
//     slug: 'opposition-party-splits-constitutional-reform-proposal',
//     excerpt: 'A faction of 14 lawmakers broke from the main opposition bench after leadership backed a controversial proposal to limit presidential term lengths.',
//     coverImage: { url: 'https://images.unsplash.com/photo-1518384401463-d3873e674435?q=80&w=2000&auto=format&fit=crop', alt: 'parliamentary floor debate' },
//     category: cat('cat-4'),
//     author: auth('author-1'),
//     status: 'published',
//     isBreaking: false,
//     isFeatured: false,
//     publishedAt: '2026-04-04T09:00:00Z',
//     readTime: 7,
//     tags: [{ tag: 'constitutional reform' }, { tag: 'opposition' }, { tag: 'politics' }],
//     createdAt: '2026-04-04T09:00:00Z',
//     updatedAt: '2026-04-04T09:00:00Z',
//   },
//   {
//     id: 'art-10',
//     title: 'International Observers Raise Concerns Over Election Transparency',
//     slug: 'international-observers-raise-concerns-election-transparency',
//     excerpt: 'A delegation from three international monitoring bodies cited irregularities in voter registration and restricted media access in their preliminary report.',
//     coverImage: { url: 'https://images.unsplash.com/photo-1557426282-081dee1d784d?q=80&w=2000&auto=format&fit=crop', alt: 'election observers' },
//     category: cat('cat-1'),
//     region: reg('reg-1'),
//     author: auth('author-2'),
//     status: 'published',
//     isBreaking: false,
//     isFeatured: false,
//     publishedAt: '2026-04-03T16:00:00Z',
//     readTime: 8,
//     tags: [{ tag: 'election' }, { tag: 'transparency' }, { tag: 'international' }],
//     createdAt: '2026-04-03T16:00:00Z',
//     updatedAt: '2026-04-03T16:00:00Z',
//   },
// ]

// export const mockLiveUpdates = [
//   {
//     id: 'live-1',
//     timestamp: '2026-04-12T11:35:00Z',
//     headline: 'Emergency session called for 14:00 local time',
//     body: 'The Speaker has convened an emergency parliamentary session to address the crisis. All lawmakers have been recalled from recess.',
//     category: 'Parliament',
//     isBreaking: true,
//   },
//   {
//     id: 'live-2',
//     timestamp: '2026-04-12T10:58:00Z',
//     headline: 'Opposition walkout after procedural dispute',
//     body: 'Forty-two opposition lawmakers left the chamber in protest after the ruling coalition rejected a motion to extend debate time.',
//     category: 'Parliament',
//     isBreaking: false,
//   },
//   {
//     id: 'live-3',
//     timestamp: '2026-04-12T10:22:00Z',
//     headline: 'Finance Minister presents amended budget proposal',
//     body: 'The minister unveiled revised spending figures that cut defense allocations by 3% while increasing health and education funding.',
//     category: 'Policy & Law',
//     isBreaking: false,
//   },
//   {
//     id: 'live-4',
//     timestamp: '2026-04-12T09:45:00Z',
//     headline: 'Protesters gather outside parliament building',
//     body: 'An estimated 2,000 demonstrators assembled outside the National Assembly, calling for the government to withdraw the emergency powers bill.',
//     category: 'Elections',
//     isBreaking: false,
//   },
//   {
//     id: 'live-5',
//     timestamp: '2026-04-12T09:10:00Z',
//     headline: 'Session opens with minute of silence for former deputy speaker',
//     body: 'Parliament observed a formal minute of silence following the passing of former Deputy Speaker Sok Hen, who served four terms in the Assembly.',
//     category: 'Parliament',
//     isBreaking: false,
//   },
// ]
